image: node:22
variables:
  AWS_ACCOUNT: "${{ values.awsAccountID }}"
  AWS_DEFAULT_REGION: "${{ values.awsRegion }}"
  ROLE_ARN: "${{values.environmentRole}}"
  OPA_PLATFORM_REGION: "${{ values.platformRegion }}"
  
stages:
  - build

include:
  - project: 'opa-admin/backstage-reference'
    ref: main 
    file:
      - 'common/cicd/.gitlab-ci-aws-provider-basic.yml'
